apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waha-sessions-pvc
  namespace: automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waha-media-pvc
  namespace: automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
