apiVersion: v1
kind: Service
metadata:
  name: waha
  namespace: automation
spec:
  type: NodePort
  selector:
    app: waha
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30030
    name: http
